server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sugw?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123233

mybatis:
  mapper-locations: classpath:/mapper/*.xml,classpath:/mapperExtension/*.xml

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger3
  try-host: http://localhost:${server.port}